name: osx-hs-common
version: 0.1.0.0
github: githubuser/osx-hs-common
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2019 Author name here
extra-source-files:
  - README.md
  - ChangeLog.md
description: >-
  Please see the README on GitHub at
  <https://github.com/githubuser/osx-hs-common#readme>
dependencies:
  - base >= 4.7 && < 5
  - base-unicode-symbols
  - unix
  - time
  - text
  - directory
  - bytestring
  - utf8-string
  - regex-posix
  - haskeline
  - filepath
  - zlib
  - QuickCheck
default-extensions:
  - UnicodeSyntax
  - OverloadedStrings
library:
  source-dirs: src
executables:
  osx-hs-common-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - osx-hs-common
tests:
  osx-hs-common-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - osx-hs-common
